# Day 33 Task
# MySQL
Exercise - 1 ![alt text](1.png)
Exercise - 2 !![alt text](2-1.png)
Exercise - 3 ![alt text](3.png)
Exercise - 4 ![alt text](4.png)
Exercise - 5 ![alt text](5.png)
Exercise - 6 ![alt text](6.png)
Exercise - 7 ![alt text](7.png)
Exercise - 8 ![alt text](8.png)
Exercise - 9 ![alt text](9.png)
Exercise - 10 ![alt text](10.png)
Exercise - 11 ![alt text](11.png)
Exercise - 12 ![alt text](12.png)
Exercise - 13 ![alt text](13.png)
Exercise - 14 ![alt text](14.png)
Exercise - 15 ![alt text](15.png)
Exercise - 16 ![alt text](16.png)
Exercise - 17 ![alt text](17.png)
Exercise - 18 ![alt text](18.png)
